# Config file for automatic testing at travis-ci.com

language: python

python:
  - 3.9
  - 3.8

cache:
  pip: true
  directories:
    - .tox

matrix:
  include:
    - python: 3.8
      env: TOXENV=lint

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U pip setuptools wheel tox tox-travis poetry

# Command to run tests, e.g. python setup.py test
script: tox

# This includes the key to our Slack channel. Delete or use yours.
notifications:
  slack:
    rooms:
      - abilian:dTtRD7DHS4Dw3jfRrqytQWU6#code
    on_success: change
    on_failure: always
